first draft of healthz with three basic checks added
kool-dev/healthz pull request #2
Opened 2020-12-09 16:08 UTC by nkabz

2020-12-09 16:13 UTC, nkabz commented on cmd/root.go
> +}
@fabriciojs thinking about moving everything here to a separete "checks.go" file/class so the command itself is a more clean and lean file

2020-12-09 16:14 UTC, nkabz commented on cmd/root.go
> +	}
those functions as well can just be a toCheck.exec(), toCheck.HTTP() and toCheck.Socket() functions, what do you think?

2020-12-09 16:30 UTC, nkabz commented on cmd/root.go
> +		fmt.Printf("Exec args parse failed with %s\n", err)
@fabriciojs Also in this first version we are simply printing values on the screen. Should we use/do something else?

2020-12-10 20:03 UTC, nkabz commented on cmd/root.go
> +		fmt.Printf("Exec args parse failed with %s\n", err)
@todo here is also exit and print the exit code

I.E.: os.Exit(0) if successful and os.Exit(1) if ewe have any errors

2020-12-17 16:59 UTC, fabriciojs requested changes
Looking good. Waiting for the completion of test suite!

2020-12-29 14:39 UTC, merged